### ISSUE TITLE
Fails in python 3

### ISSUE THREAD

**Issue by naught101** [ssj71/kboard-editor#2]
```{python}
In [1]: import kboard
ALSA lib conf.c:3009:(snd_config_update_r) Cannot access file /etc/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
---------------------------------------------------------------------------
MidiException                             Traceback (most recent call last)
<ipython-input-1-0b8ee74ed658> in <module>()
----> 1 import kboard

/data/documents/electronics/kboard-editor/kboard.py in <module>()
     26 #it would be nice if these were constants
     27 midi.init()
---> 28 midi_out = midi.Output(midi.get_default_output_id())
     29 hi = [0xf0, 0x7e, 0x7f, 0x07, 0x06, 0x01, 0xf7]
     30 default = [

/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/pygame/midi.py in __init__(self, device_id, latency, buffer_size)
    387 
    388         if device_id == -1:
--> 389             raise MidiException("Device id is -1, not a valid output id.  -1 usually means there were no default Output devices.")
    390 
    391         try:

MidiException: 'Device id is -1, not a valid output id.  -1 usually means there were no default Output devices.'
```

This kind of looks like a problem with pygame, really, because it works fine in python2, and I can't see how your code is different between versions, but I figured you may have hit this, and might know what's causing it.

**Comment by ssj71** [comment]
well, I know when I wrote this, ubuntu/debian doesn't ship a package that has pygame for python3, so to use it there you must build pygame yourself. I've never bothered to do this. 

From the message there it seems that python 3 doesn't have the default midi port set like py2 does. So I'll probably have to list the outputs and select the proper one somehow. I'll see if I can test this and get it working. I in general prefer python3.

**Comment by naught101** [comment]
I'm more certain that this is a pygame bug now, so I posted on the pygame issue queue: https://bitbucket.org/pygame/pygame/issues/327/cant-use-pygame-midi-on-linux-python3

I'll close this, and re-open if later if it seems necessary. Sorry for the spurious post.
