### ISSUE TITLE
question leds?

### ISSUE THREAD

**Issue by s0len0id** [ssj71/kboard-editor#4]
cool, how did you find the sysex?
Have you managed to light the leds programmatically? Different note/velocity values perhaps as for the qunexus keyboard?

thx.

**Comment by ssj71** [comment]
I just used their kboard app on windows and looked at the usb midi data and brute forced it. I couldn't learn anything through this method that wasn't exposed through their app so I have no idea for those sorts of features. You can tinker with the other values in the sysex by editing the source code. If you learn anything please share!

**Comment by s0len0id** [comment]
the kboard LEDs appear to react similar to what is in the 2 qunexus manuals:
note-on messages 25 to 51, with velocity 0 through, I guess 16, for different brightness. 0 Being off, and 16 levels is mentioned in the larger of the 2 qunexus manuals (the qunexus-red manual is more concise, but perhaps describes less).

Btw, the IOS Navichord app recognizes the KMI boards, but I couldn't convince the Midiwrench app to log anything, must be doing something wrong.

Btw2: about Linux compatibility, KMI hosts a browser based configuration app for the boards (webmidi), might be easier to reverse engineer. I imagine the qunexus hardware being similar to the kboard on the inside...

**Comment by s0len0id** [comment]
in java :)
https://github.com/s0len0id/midiledchecker
